schema_controller:
  resource: ../src/JsonSchema/Controller/
  type: attribute

security_session_controller:
  resource: ../src/BoundedContext/Security/Session/Controller/
  type: attribute

security_session_controller_for_projection_reaction:
  resource: ../src/BoundedContext/Security/Session/ControllerForProjectionReaction/
  type: attribute