schema_controller:
  resource: ../src/JsonSchema/Controller/
  type: attribute

creditcardproduct_product_controller:
  resource: ../src/BoundedContext/CreditCardProduct/Product/Controller/
  type: attribute

creditcardproduct_product_controller_for_projection_reaction:
  resource: ../src/BoundedContext/CreditCardProduct/Product/ControllerForProjectionReaction
  type: attribute